fos_rest:
  param_fetcher_listener: true
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: violations
  view:
    formats: { json: true, xml: false, rss: false }
    view_response_listener: true
  serializer:
    serialize_null: true
  format_listener:
    rules:
      - { path: "^/", fallback_format: "json", priorities: ["json"] }

sensio_framework_extra:
  request: { converters: true }